# Generated by Django 3.0.7 on 2020-06-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.CharField(help_text='Ingrese ID de la producto', max_length=10, primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(help_text='Ingrese Nombre de la producto', max_length=200)),
                ('producto_valor', models.IntegerField(help_text='Ingrese el precio de la producto (Ej: $ 999 999).')),
                ('producto_descripcion', models.TextField(help_text='Ingrese la descripcion de la producto', max_length=3000)),
                ('producto_imagen', models.ImageField(null=True, upload_to='gallery')),
            ],
        ),
    ]
